name: azizi_tarany
description: Azizi Tarany - Pashto audio collection
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.6

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
